theme: minima
title: "Today I Learned: 'A Potpourri of Posts'"
author: Adam Taitano
email: adam.taitano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Personal Blog for Adam Taitano. Contains "About" and "Posts" Sections.
  Each post may mention topics about learning software development, security,
  artificial intelligence, or even music and writing.

# social links
twitter_username: AdamTaitano # DO NOT include the @ character, or else the build will fail!
github_username:  adamtaitano # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
